// react-project/src/components/gallery/ProjectGalleryButton.tsx
import React from 'react';
import { motion } from 'motion/react';
import { ArrowRight } from 'lucide-react';

interface ProjectGalleryButtonProps {
  onClick: () => void;
  imageCount?: number;
  label?: string;
  className?: string;
}

export const ProjectGalleryButton: React.FC<ProjectGalleryButtonProps> = ({
  onClick,
  imageCount,
  label = "Explore Project Gallery",
  className = ""
}) => {
  return (
    <motion.button
      type="button"
      onClick={onClick}
      whileHover={{ y: -2 }}
      whileTap={{ scale: 0.98 }}
      transition={{ duration: 0.25, ease: [0.16, 1, 0.3, 1] }}
      aria-label={`${label}${imageCount ? ` (${imageCount} photos)` : ''}`}
      className={`group relative inline-flex items-center gap-3 bg-white text-primary border border-primary hover:bg-primary hover:text-white font-mono text-xs md:text-sm font-bold uppercase tracking-[0.18em] px-8 py-3.5 rounded-full shadow-sm hover:shadow-md hover:shadow-primary/20 transition-all duration-300 focus:outline-none focus:ring-4 focus:ring-primary/20 cursor-pointer ${className}`}
    >
      <span className="relative z-10">{label}</span>

      {imageCount !== undefined && imageCount > 0 && (
        <span className="px-2.5 py-0.5 rounded-full bg-primary/10 text-primary group-hover:bg-white/20 group-hover:text-white font-mono text-[10px] font-bold tracking-normal transition-colors">
          {imageCount}
        </span>
      )}

      {/* Horizontal Right Arrow Icon matching reference image */}
      <ArrowRight className="w-4 h-4 text-primary group-hover:text-white transition-transform duration-300 group-hover:translate-x-1" />
    </motion.button>
  );
};

// src/app/shared/components/project-gallery-button/project-gallery-button.component.ts
import { Component, input, output } from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';

@Component({
  selector: 'app-project-gallery-button',
  imports: [TranslatePipe],
  template: `
    <button
      type="button"
      (click)="buttonClick.emit()"
      [attr.aria-label]="label() + (imageCount() ? ' (' + imageCount() + ' photos)' : '')"
      class="group relative inline-flex items-center gap-3 bg-white text-primary border border-primary hover:bg-primary hover:text-white font-mono text-xs md:text-sm font-bold uppercase tracking-[0.18em] px-8 py-3.5 rounded-full shadow-sm hover:shadow-md hover:shadow-primary/20 transition-all duration-300 focus:outline-none focus:ring-4 focus:ring-primary/20 cursor-pointer"
    >
      <span class="relative z-10">{{ label() | translate }}</span>

      @if (imageCount() && imageCount()! > 0) {
        <span class="px-2.5 py-0.5 rounded-full bg-primary/10 text-primary group-hover:bg-white/20 group-hover:text-white font-mono text-[10px] font-bold tracking-normal transition-colors">
          {{ imageCount() }}
        </span>
      }

      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="text-primary group-hover:text-white transition-transform duration-300 group-hover:translate-x-1 rtl:rotate-180"><path d="M5 12h14"/><path d="m12 5 7 7-7 7"/></svg>
    </button>
  `
})
export class ProjectGalleryButtonComponent {
  readonly label = input<string>('View Project Gallery');
  readonly imageCount = input<number>(0);

  readonly buttonClick = output<void>();
}
