// src/app/shared/components/footer/footer.component.ts
import { Component, inject, output } from '@angular/core';
import { RouterLink, Router } from '@angular/router';
import { TranslatePipe } from '@ngx-translate/core';
import { ProfileService } from '../../../core/services/profile.service';
import { ImageComponent } from '../image/image.component';

export interface SocialLinkItem {
  name: string;
  href: string;
  iconSvg: string;
}

@Component({
  selector: 'app-footer',
  imports: [RouterLink, ImageComponent, TranslatePipe],
  templateUrl: './footer.component.html',
})
export class FooterComponent {
  readonly profileService = inject(ProfileService);
  private readonly router = inject(Router);
  readonly openQuoteModal = output<void>();

  readonly socialLinks: SocialLinkItem[] = [
    {
      name: 'LinkedIn',
      href: 'https://linkedin.com/company/digitalbond',
      iconSvg: 'M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6zM2 9h4v12H2zM4 2a2 2 0 1 0 0 4 2 2 0 0 0 0-4z',
    },
    {
      name: 'Facebook',
      href: 'https://facebook.com/digitalbond',
      iconSvg: 'M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z',
    },
    {
      name: 'Instagram',
      href: 'https://instagram.com/digitalbond',
      iconSvg: 'M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z',
    },
    {
      name: 'X',
      href: 'https://x.com/digitalbond',
      iconSvg: 'M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z',
    },
    {
      name: 'YouTube',
      href: 'https://youtube.com/digitalbond',
      iconSvg: 'M22.54 6.42a2.78 2.78 0 0 0-1.94-1.96C18.88 4 12 4 12 4s-6.88 0-8.6.46a2.78 2.78 0 0 0-1.94 1.96A29 29 0 0 0 1 12a29 29 0 0 0 .46 5.58a2.78 2.78 0 0 0 1.94 1.96c1.72.46 8.6.46 8.6.46s6.88 0 8.6-.46a2.78 2.78 0 0 0 1.94-1.96A29 29 0 0 0 23 12a29 29 0 0 0-.46-5.58zM9.75 15.02V8.98L15.5 12l-5.75 3.02z',
    },
  ];

  readonly quickLinks = [
    { label: 'Home', path: '/' },
    { label: 'About', path: '/about' },
    { label: 'Solutions', path: '/solutions' },
    { label: 'Projects', path: '/projects' },
    { label: 'Industries', path: '/industries' },
    { label: 'Clients & Partners', path: '/clients-partners' },
    { label: 'Blogs', path: '/blogs' },
  ];

  readonly resourceLinks = [
    { label: 'Company Profile ↓', path: '/about#profile' },
    { label: 'Privacy Policy', path: '/privacy' },
    { label: 'Contact Us', path: '/contact' },
  ];

  downloadProfile(): void {
    this.profileService.downloadProfile();
  }

  triggerQuote(): void {
    this.openQuoteModal.emit();
  }

  handleFooterLinkClick(event: MouseEvent, path: string): void {
    if (path.includes('#')) {
      const [pagePath, hash] = path.split('#');
      const currentUrl = this.router.url.split('#')[0];

      if (currentUrl === pagePath || (pagePath === '' && currentUrl === '/')) {
        const element = document.getElementById(hash);
        if (element) {
          event.preventDefault();
          element.scrollIntoView({ behavior: 'smooth' });
        }
      }
    } else {
      window.scrollTo({ top: 0, behavior: 'smooth' });
    }
  }
}

<footer id="global-footer"
  class="w-full min-w-full max-w-none bg-[#142b52] text-white relative overflow-hidden pt-20 pb-10 border-t-[3px] border-primary">
  <!-- Subtle radial overlay for visual depth -->
  <div
    class="absolute inset-0 bg-[radial-gradient(circle_at_top,var(--tw-gradient-stops))] from-[#325A9E] via-transparent to-transparent pointer-events-none">
  </div>

  <!-- Authentic Engineering Blueprint Pattern Background -->
  <div class="absolute inset-0 pointer-events-none select-none overflow-hidden">
    <!-- Subtle engineering grid pattern -->
    <svg class="absolute inset-0 w-full h-full" xmlns="http://www.w3.org/2000/svg">
      <defs>
        <pattern id="footer-blueprint-grid" width="80" height="80" patternUnits="userSpaceOnUse">
          <path d="M 80 0 L 0 0 0 80" fill="none" stroke="white" stroke-width="1" opacity="0.08" />
          <path d="M 40 0 L 40 80 M 0 40 L 80 40" fill="none" stroke="white" stroke-width="0.5" stroke-dasharray="2,4"
            opacity="0.04" />
        </pattern>
        <pattern id="footer-blueprint-dots" width="20" height="20" patternUnits="userSpaceOnUse">
          <circle cx="2" cy="2" r="1.5" fill="#EA8A22" opacity="0.08" />
        </pattern>
      </defs>
      <rect width="100%" height="100%" fill="url(#footer-blueprint-grid)" />
      <rect width="100%" height="100%" fill="url(#footer-blueprint-dots)" />
    </svg>

    <!-- Blueprint technical vector graphics positioned on the edges -->
    <svg class="absolute right-0 bottom-0 w-150 h-100 text-white opacity-[0.06] translate-x-20 translate-y-20"
      viewBox="0 0 600 400" fill="none" stroke="currentColor" stroke-width="0.75">
      <circle cx="300" cy="200" r="180" stroke-dasharray="4,8" />
      <circle cx="300" cy="200" r="120" stroke="#EA8A22" opacity="0.8" stroke-width="1.5" />
      <circle cx="300" cy="200" r="60" stroke-dasharray="1,4" />

      <line x1="100" y1="200" x2="500" y2="200" stroke-dasharray="8,4" />
      <line x1="300" y1="0" x2="300" y2="400" stroke-dasharray="8,4" />
      <line x1="150" y1="50" x2="450" y2="350" />
      <line x1="150" y1="350" x2="450" y2="50" />

      <path d="M 120,180 L 120,220 M 480,180 L 480,220" stroke="#EA8A22" stroke-width="1.5" />
      <path d="M 120,200 L 480,200" />

      <path d="M 350,200 A 50,50 0 0,0 335,165" stroke-width="1.5" stroke="#EA8A22" />
      <text x="360" y="180" fill="#EA8A22" font-size="12" font-family="monospace" font-weight="bold">45.0°</text>
    </svg>

    <svg class="absolute left-0 top-0 w-100 h-75 text-white opacity-[0.05] -translate-x-12 -translate-y-12"
      viewBox="0 0 400 300" fill="none" stroke="currentColor" stroke-width="0.75">
      <path d="M 50,250 L 150,150 L 350,250 Z" stroke-width="1" />
      <line x1="150" y1="150" x2="150" y2="250" stroke-dasharray="4,4" stroke="#EA8A22" stroke-width="1.5" />
      <line x1="100" y1="200" x2="150" y2="250" />
      <line x1="250" y1="200" x2="150" y2="250" />
      <line x1="250" y1="200" x2="250" y2="250" stroke="#EA8A22" stroke-width="1.5" />
      <line x1="100" y1="200" x2="100" y2="250" stroke="#EA8A22" stroke-width="1.5" />

      <text x="15" y="255" fill="currentColor" font-size="10" font-family="monospace">A-1</text>
      <text x="145" y="265" fill="#EA8A22" font-size="10" font-family="monospace" font-weight="bold">A-2</text>
      <text x="355" y="255" fill="currentColor" font-size="10" font-family="monospace">A-3</text>
    </svg>

    <!-- Crane Outline in Bottom Left Corner -->
    <svg class="absolute left-10 bottom-10 w-60 h-80 text-white opacity-[0.06] pointer-events-none hidden md:block"
      viewBox="0 0 240 320" fill="none" stroke="currentColor" stroke-width="0.8">
      <line x1="80" y1="320" x2="80" y2="100" />
      <line x1="90" y1="320" x2="90" y2="100" />
      <line x1="80" y1="320" x2="90" y2="300" />
      <line x1="90" y1="300" x2="80" y2="280" />
      <line x1="80" y1="280" x2="90" y2="260" />
      <line x1="90" y1="260" x2="80" y2="240" />
      <line x1="80" y1="240" x2="90" y2="220" />
      <line x1="90" y1="220" x2="80" y2="200" />
      <line x1="80" y1="200" x2="90" y2="180" />
      <line x1="90" y1="180" x2="80" y2="160" />
      <line x1="80" y1="160" x2="90" y2="140" />
      <line x1="90" y1="140" x2="80" y2="120" />
      <line x1="80" y1="120" x2="90" y2="100" />
      <line x1="10" y1="100" x2="230" y2="100" stroke-width="1.2" />
      <line x1="10" y1="105" x2="80" y2="105" />
      <line x1="10" y1="100" x2="10" y2="105" />
      <rect x="75" y="85" width="15" height="15" fill="none" />
      <line x1="80" y1="85" x2="95" y2="60" />
      <line x1="95" y1="60" x2="110" y2="100" />
      <line x1="10" y1="100" x2="95" y2="60" stroke-dasharray="2,2" />
      <line x1="180" y1="100" x2="95" y2="60" stroke-dasharray="2,2" />
      <rect x="150" y="100" width="8" height="5" fill="none" />
      <line x1="154" y1="105" x2="154" y2="140" />
      <path d="M 152,140 Q 154,144 156,140" />
    </svg>

    <!-- Building Wireframe in Top Right Corner -->
    <svg class="absolute right-12 top-12 w-50 h-75 text-white opacity-[0.06] pointer-events-none hidden lg:block"
      viewBox="0 0 200 300" fill="none" stroke="currentColor" stroke-width="0.8">
      <line x1="20" y1="280" x2="180" y2="280" />
      <line x1="20" y1="240" x2="180" y2="240" />
      <line x1="20" y1="200" x2="180" y2="200" />
      <line x1="20" y1="160" x2="180" y2="160" />
      <line x1="20" y1="120" x2="180" y2="120" />
      <line x1="20" y1="80" x2="180" y2="80" />
      <line x1="20" y1="40" x2="180" y2="40" />

      <line x1="20" y1="40" x2="20" y2="280" />
      <line x1="60" y1="40" x2="60" y2="280" />
      <line x1="100" y1="40" x2="100" y2="280" />
      <line x1="140" y1="40" x2="140" y2="280" />
      <line x1="180" y1="40" x2="180" y2="280" />

      <line x1="20" y1="40" x2="60" y2="80" stroke-dasharray="2,2" />
      <line x1="60" y1="40" x2="20" y2="80" stroke-dasharray="2,2" />
      <line x1="100" y1="80" x2="140" y2="120" stroke-dasharray="2,2" />
      <line x1="140" y1="80" x2="100" y2="120" stroke-dasharray="2,2" />
      <line x1="140" y1="160" x2="180" y2="200" stroke-dasharray="2,2" />
      <line x1="180" y1="160" x2="140" y2="200" stroke-dasharray="2,2" />
    </svg>
  </div>

  <div
    class="max-w-350 mx-auto px-5 md:px-6 lg:px-7 xl:px-8 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-12 gap-12 mb-16 relative z-10">
    <!-- Column 1: Brand Info -->
    <div class="lg:col-span-4 flex flex-col items-start relative">
      <!-- Logo Brand Group -->
      <div class="-mt-7 -ml-6 -mb-2 text-white w-full max-w-50 relative z-20">
        <img src="/main-logo-white.webp" alt="Maabany Logo" class="w-full h-auto object-contain" />
      </div>

      <p class="text-[14px] text-white/80 leading-[1.8] font-light pr-4">
        {{ webInfoService?.footerDescription() || ('Maabany Integrated Building Solutions delivers innovative
        engineering, construction, and facility management services across the Kingdom of Saudi Arabia (KSA) with a
        commitment to quality, precision, and long-term value.' | translate) }}
      </p>

      <!-- Social Media Links -->
      <div class="flex items-center gap-3 pt-4">
        @for (social of socialLinks(); track social?.name) {
        <a [href]="social?.href" target="_blank" rel="noopener noreferrer" [title]="social?.name"
          class="w-9 h-9 rounded-full border border-white/20 flex items-center justify-center text-white/70 hover:text-white hover:border-primary hover:bg-primary transition-all duration-250 transform hover:scale-110">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none"
            stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="w-4 h-4">
            <path [attr.d]="social.iconSvg" />
          </svg>
        </a>
        }
      </div>
    </div>

    <div class="lg:col-span-3 space-y-6">
      <span
        class="text-[18px] block font-semibold text-white tracking-wide relative pb-2 after:content-[''] after:absolute after:bottom-0 after:inset-s-0 after:w-8 after:h-0.5 after:bg-primary">
        {{ 'FOOTER.QUICK_LINKS' | translate }}
      </span>
      <ul class="grid grid-cols-1 gap-3.5">
        @for (link of quickLinks; track link?.path) {
        <li>
          <a [routerLink]="link?.path ? ['/', lang, link?.path] : ['/', lang]"
            class="text-[15px] text-white/80 hover:text-primary transition-all duration-300 inline-flex items-center gap-2 group relative py-1">
            <span
              class="w-1.5 h-1.5 rounded-full bg-white/20 group-hover:bg-primary group-hover:shadow-[0_0_8px_rgba(234,138,34,0.6)] transition-all"></span>
            <span class="relative">
              {{ link?.label | translate }}
              <span
                class="absolute bottom-0 left-0 w-0 h-[1.5px] bg-primary transition-all duration-300 group-hover:w-full"></span>
            </span>
          </a>
        </li>
        }
      </ul>
    </div>

    <div class="lg:col-span-2 space-y-6">
      <span
        class="text-[18px] block font-semibold text-white tracking-wide relative pb-2 after:content-[''] after:absolute after:bottom-0 after:inset-s-0 after:w-8 after:h-0.5 after:bg-primary">
        {{ 'FOOTER.RESOURCES' | translate }}
      </span>
      <ul class="grid grid-cols-1 gap-3.5 mb-6">
        @for (link of resourceLinks; track link.path) {
        <li>
          @if (link.label.includes('Company Profile')) {
          <button (click)="downloadProfile()" [disabled]="profileService?.isDownloading()"
            class="text-[15px] text-white/80 hover:text-primary text-left transition-all duration-300 inline-flex items-center gap-2 group cursor-pointer focus:outline-none relative py-1">
            <span
              class="w-1.5 h-1.5 rounded-full bg-white/20 group-hover:bg-primary group-hover:shadow-[0_0_8px_rgba(234,138,34,0.6)] transition-all"></span>
            <span class="relative">
              {{ profileService?.isDownloading() ? ('Downloading Profile...' | translate) : ('Company Profile ↓' |
              translate) }}
              <span
                class="absolute bottom-0 left-0 w-0 h-[1.5px] bg-primary transition-all duration-300 group-hover:w-full"></span>
            </span>
          </button>
          } @else {
          <a [routerLink]="['/',lang,link?.path]"
            class="text-[15px] text-white/80 hover:text-primary transition-all duration-300 inline-flex items-center gap-2 group relative py-1">
            <span
              class="w-1.5 h-1.5 rounded-full bg-white/20 group-hover:bg-primary group-hover:shadow-[0_0_8px_rgba(234,138,34,0.6)] transition-all"></span>
            <span class="relative">
              {{ link?.label | translate }}
              <span
                class="absolute bottom-0 left-0 w-0 h-[1.5px] bg-primary transition-all duration-300 group-hover:w-full"></span>
            </span>
          </a>
          }
        </li>
        }
        <li>
          <a [routerLink]="'request-a-quote'"
            class="text-[15px] text-white/80 hover:text-primary text-left transition-all duration-300 inline-flex items-center gap-2 group cursor-pointer focus:outline-none relative py-1">
            <span
              class="w-1.5 h-1.5 rounded-full bg-white/20 group-hover:bg-primary group-hover:shadow-[0_0_8px_rgba(234,138,34,0.6)] transition-all"></span>
            <span class="relative">
              {{ 'NAV.REQUEST_QUOTE' | translate }}
              <span
                class="absolute bottom-0 left-0 w-0 h-[1.5px] bg-primary transition-all duration-300 group-hover:w-full"></span>
            </span>
          </a>
        </li>
      </ul>
    </div>

    <!-- Column 4: Contact Us -->
    <div class="lg:col-span-3 space-y-6">
      <span
        class="text-[18px] block font-semibold text-white tracking-wide relative pb-2 after:content-[''] after:absolute after:bottom-0 after:inset-s-0 after:w-8 after:h-0.5 after:bg-primary">
        {{ 'FOOTER.CONTACT_US' | translate }}
      </span>
      <div class="space-y-4 text-[14px] text-white/75 font-light">
        <div class="flex gap-3 items-start group">
          <div
            class="p-2.5 rounded-xl border border-white/15 text-primary shrink-0 group-hover:bg-primary group-hover:text-white transition-all duration-300">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none"
              stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="w-4 h-4">
              <path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z" />
              <circle cx="12" cy="10" r="3" />
            </svg>
          </div>
          <div class="space-y-1 mt-0.5">
            <p class="font-medium text-white text-[14px]">{{ 'Saudi Arabia HQ' | translate }}</p>
            <a href="https://maps.google.com/?q=2923+Al-Sharif+Ahmed+bin+Abdul+Muttalib,+Al-Salhiya+District,+Jeddah,+Saudi+Arabia"
              target="_blank" rel="noopener noreferrer"
              class="text-white/60 text-[12px] leading-relaxed hover:text-primary transition-colors block">
              2923 Al-Sharif Ahmed bin Abdul Muttalib, Al-Salhiya District, Jeddah, Saudi Arabia
            </a>
          </div>
        </div>

        <div class="flex gap-3 items-start group">
          <div
            class="p-2.5 rounded-xl border border-white/15 text-primary shrink-0 group-hover:bg-primary group-hover:text-white transition-all duration-300">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none"
              stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="w-4 h-4">
              <path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z" />
              <circle cx="12" cy="10" r="3" />
            </svg>
          </div>
          <div class="space-y-1 mt-0.5">
            <p class="font-medium text-white text-[14px]">{{ 'Cairo Hub (Egypt)' | translate }}</p>
            <a href="https://maps.google.com/?q=53+Hassan+El+Sherif+Street,+Nasr+City,+Cairo,+Egypt" target="_blank"
              rel="noopener noreferrer"
              class="text-white/60 text-[12px] leading-relaxed hover:text-primary transition-colors block">
              53 Hassan El Sherif Street, Nasr City, Cairo, Egypt
            </a>
          </div>
        </div>

        <div class="flex gap-3 items-start">
          <div class="p-2.5 rounded-xl border border-white/15 text-primary shrink-0">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none"
              stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="w-4 h-4">
              <rect width="20" height="16" x="2" y="4" rx="2" />
              <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
            </svg>
          </div>
          <div class="space-y-1 mt-0.5">
            <p class="font-medium text-white text-[14px]">Email</p>
            <a [href]="'mailto:' + (webInfoService?.email() || 'info@mabany.com')"
              class="text-white/60 text-[12px] hover:text-primary transition-colors focus:outline-none focus:underline block">
              {{ webInfoService?.email() || 'info@mabany.com' }}
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Bottom Copyright Bar & Tech House Brand -->
  <div
    class="max-w-7xl mx-auto px-6 lg:px-8 pt-8 border-t border-white/15 flex flex-col sm:flex-row items-center justify-center gap-y-2 gap-x-4 sm:gap-x-6 text-[14px] text-white/60 relative z-10 text-center">
    <p>{{ 'All Rights Reserved © 2026' | translate }}</p>
    <div class="hidden sm:block w-px h-3.5 bg-white/15"></div>
    <div class="flex items-center gap-2">
      <span class="text-[12px] text-white/60">{{ 'Powered by' | translate }}</span>
      <a href="https://techhouseksa.com/" target="_blank" title="tech house KSA" rel="noopener noreferrer"
        class="inline-flex items-center">
        <app-image src="/techhouse-logo.webp" alt="tech house KSA" [width]="24" [height]="24"
          class="h-7 md:h-8 w-auto opacity-95 hover:opacity-100 transition-opacity cursor-pointer" />
      </a>
    </div>
  </div>
</footer>

// react-project/src/components/Footer.tsx
import React from 'react';
import { Link, useLocation } from 'react-router-dom';
import { motion } from 'motion/react';
import { downloadCompanyProfile } from '../utils/profileDownloader';

import whiteMabLogo from '../assets/images/Maabany white.png';
import techHouseLogo from '../assets/images/TEH V 2.png';

import {
  Linkedin,
  Facebook,
  Instagram,
  Youtube,
  X,
  MapPin,
  Mail
} from 'lucide-react';

interface FooterProps {
  setQuoteModalOpen: (open: boolean) => void;
}

export function Footer({ setQuoteModalOpen }: FooterProps) {
  const location = useLocation();

  const handleFooterLinkClick = (e: React.MouseEvent<HTMLAnchorElement>, path: string) => {
    if (path.includes('#')) {
      const [pagePath, hash] = path.split('#');
      if (location.pathname === pagePath || (pagePath === '' && location.pathname === '/')) {
        const element = document.getElementById(hash);
        const scroller = document.getElementById('app-scroller');
        if (element && scroller) {
          e.preventDefault();
          const rect = element.getBoundingClientRect();
          const targetScrollTop = scroller.scrollTop + rect.top - 100;
          scroller.scrollTo({
            top: Math.max(0, targetScrollTop),
            behavior: 'smooth'
          });
        }
      }
    } else if (location.pathname === path) {
      const scroller = document.getElementById('app-scroller');
      if (scroller) {
        e.preventDefault();
        scroller.scrollTo({
          top: 0,
          behavior: 'smooth'
        });
      }
    }
  };

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.12,
      },
    },
  };

  const columnVariants = {
    hidden: { opacity: 0, y: 30 },
    visible: {
      opacity: 1,
      y: 0,
      transition: {
        duration: 0.8,
        ease: 'easeOut',
      },
    },
  };

  const socialLinks = [
    { icon: Linkedin, href: 'https://linkedin.com/company/digitalbond', name: 'LinkedIn' },
    { icon: Facebook, href: 'https://facebook.com/digitalbond', name: 'Facebook' },
    { icon: Instagram, href: 'https://instagram.com/digitalbond', name: 'Instagram' },
    { icon: X, href: 'https://x.com/digitalbond', name: 'X' },
    { icon: Youtube, href: 'https://youtube.com/digitalbond', name: 'YouTube' },
  ];

  const quickLinks = [
    { label: 'Home', path: '/' },
    { label: 'About', path: '/about' },
    { label: 'Solutions', path: '/solutions' },
    { label: 'Projects', path: '/projects' },
    { label: 'Industries', path: '/industries' },
    { label: 'Clients & Partners', path: '/clients-partners' },
    { label: 'Blogs', path: '/blogs' },
  ];

  const resourceLinks = [
    { label: 'Company Profile', path: '/about#profile' },
    { label: 'Privacy Policy', path: '/privacy' },
    { label: 'Contact', path: '/contact' },
  ];

  return (
    <footer id="global-footer" className="w-full min-w-full max-w-none bg-[#142b52] text-white relative overflow-hidden pt-20 pb-10 border-t-[3px] border-primary">
      {/* Subtle radial overlay for visual depth */}
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_top,_var(--tw-gradient-stops))] from-[#325A9E] via-transparent to-transparent pointer-events-none" />

      {/* Authentic Engineering Blueprint Pattern Background */}
      <div className="absolute inset-0 pointer-events-none select-none overflow-hidden">
        {/* Subtle engineering grid pattern */}
        <svg className="absolute inset-0 w-full h-full" xmlns="http://www.w3.org/2000/svg">
          <defs>
            <pattern id="footer-blueprint-grid" width="80" height="80" patternUnits="userSpaceOnUse">
              <path d="M 80 0 L 0 0 0 80" fill="none" stroke="white" strokeWidth="1" opacity="0.08" />
              <path d="M 40 0 L 40 80 M 0 40 L 80 40" fill="none" stroke="white" strokeWidth="0.5" strokeDasharray="2,4" opacity="0.04" />
            </pattern>
            <pattern id="footer-blueprint-dots" width="20" height="20" patternUnits="userSpaceOnUse">
              <circle cx="2" cy="2" r="1.5" fill="#EA8A22" opacity="0.08" />
            </pattern>
          </defs>
          <rect width="100%" height="100%" fill="url(#footer-blueprint-grid)" />
          <rect width="100%" height="100%" fill="url(#footer-blueprint-dots)" />
        </svg>

        {/* Blueprint technical vector graphics positioned on the edges */}
        <svg className="absolute right-0 bottom-0 w-[600px] h-[400px] text-white opacity-[0.06] translate-x-20 translate-y-20" viewBox="0 0 600 400" fill="none" stroke="currentColor" strokeWidth="0.75">
          <circle cx="300" cy="200" r="180" strokeDasharray="4,8" />
          <circle cx="300" cy="200" r="120" stroke="#EA8A22" opacity="0.8" strokeWidth="1.5" />
          <circle cx="300" cy="200" r="60" strokeDasharray="1,4" />

          <line x1="100" y1="200" x2="500" y2="200" strokeDasharray="8,4" />
          <line x1="300" y1="0" x2="300" y2="400" strokeDasharray="8,4" />
          <line x1="150" y1="50" x2="450" y2="350" />
          <line x1="150" y1="350" x2="450" y2="50" />

          <path d="M 120,180 L 120,220 M 480,180 L 480,220" stroke="#EA8A22" strokeWidth="1.5" />
          <path d="M 120,200 L 480,200" />

          <path d="M 350,200 A 50,50 0 0,0 335,165" strokeWidth="1.5" stroke="#EA8A22" />
          <text x="360" y="180" fill="#EA8A22" fontSize="12" fontFamily="monospace" fontWeight="bold">45.0°</text>
        </svg>

        <svg className="absolute left-0 top-0 w-[400px] h-[300px] text-white opacity-[0.05] -translate-x-12 -translate-y-12" viewBox="0 0 400 300" fill="none" stroke="currentColor" strokeWidth="0.75">
          <path d="M 50,250 L 150,150 L 350,250 Z" strokeWidth="1" />
          <line x1="150" y1="150" x2="150" y2="250" strokeDasharray="4,4" stroke="#EA8A22" strokeWidth="1.5" />
          <line x1="100" y1="200" x2="150" y2="250" />
          <line x1="250" y1="200" x2="150" y2="250" />
          <line x1="250" y1="200" x2="250" y2="250" stroke="#EA8A22" strokeWidth="1.5" />
          <line x1="100" y1="200" x2="100" y2="250" stroke="#EA8A22" strokeWidth="1.5" />

          <text x="15" y="255" fill="currentColor" fontSize="10" fontFamily="monospace">A-1</text>
          <text x="145" y="265" fill="#EA8A22" fontSize="10" fontFamily="monospace" fontWeight="bold">A-2</text>
          <text x="355" y="255" fill="currentColor" fontSize="10" fontFamily="monospace">A-3</text>
        </svg>

        {/* Crane Outline in Bottom Left Corner */}
        <svg
          className="absolute left-10 bottom-10 w-[240px] h-[320px] text-white opacity-[0.06] pointer-events-none hidden md:block"
          viewBox="0 0 240 320"
          fill="none"
          stroke="currentColor"
          strokeWidth="0.8"
        >
          {/* Crane tower */}
          <line x1="80" y1="320" x2="80" y2="100" />
          <line x1="90" y1="320" x2="90" y2="100" />
          {/* Crane bracing */}
          <line x1="80" y1="320" x2="90" y2="300" />
          <line x1="90" y1="300" x2="80" y2="280" />
          <line x1="80" y1="280" x2="90" y2="260" />
          <line x1="90" y1="260" x2="80" y2="240" />
          <line x1="80" y1="240" x2="90" y2="220" />
          <line x1="90" y1="220" x2="80" y2="200" />
          <line x1="80" y1="200" x2="90" y2="180" />
          <line x1="90" y1="180" x2="80" y2="160" />
          <line x1="80" y1="160" x2="90" y2="140" />
          <line x1="90" y1="140" x2="80" y2="120" />
          <line x1="80" y1="120" x2="90" y2="100" />
          {/* Jib */}
          <line x1="10" y1="100" x2="230" y2="100" strokeWidth="1.2" />
          {/* Counter Jib */}
          <line x1="10" y1="105" x2="80" y2="105" />
          <line x1="10" y1="100" x2="10" y2="105" />
          {/* Cab */}
          <rect x="75" y="85" width="15" height="15" fill="none" />
          {/* A-Frame */}
          <line x1="80" y1="85" x2="95" y2="60" />
          <line x1="95" y1="60" x2="110" y2="100" />
          {/* Cables */}
          <line x1="10" y1="100" x2="95" y2="60" strokeDasharray="2,2" />
          <line x1="180" y1="100" x2="95" y2="60" strokeDasharray="2,2" />
          {/* Trolley and Hook */}
          <rect x="150" y="100" width="8" height="5" fill="none" />
          <line x1="154" y1="105" x2="154" y2="140" />
          <path d="M 152,140 Q 154,144 156,140" />
        </svg>

        {/* Building Wireframe in Top Right Corner */}
        <svg
          className="absolute right-12 top-12 w-[200px] h-[300px] text-white opacity-[0.06] pointer-events-none hidden lg:block"
          viewBox="0 0 200 300"
          fill="none"
          stroke="currentColor"
          strokeWidth="0.8"
        >
          {/* Floors */}
          <line x1="20" y1="280" x2="180" y2="280" />
          <line x1="20" y1="240" x2="180" y2="240" />
          <line x1="20" y1="200" x2="180" y2="200" />
          <line x1="20" y1="160" x2="180" y2="160" />
          <line x1="20" y1="120" x2="180" y2="120" />
          <line x1="20" y1="80" x2="180" y2="80" />
          <line x1="20" y1="40" x2="180" y2="40" />

          {/* Columns */}
          <line x1="20" y1="40" x2="20" y2="280" />
          <line x1="60" y1="40" x2="60" y2="280" />
          <line x1="100" y1="40" x2="100" y2="280" />
          <line x1="140" y1="40" x2="140" y2="280" />
          <line x1="180" y1="40" x2="180" y2="280" />

          {/* Cross braces */}
          <line x1="20" y1="40" x2="60" y2="80" strokeDasharray="2,2" />
          <line x1="60" y1="40" x2="20" y2="80" strokeDasharray="2,2" />
          <line x1="100" y1="80" x2="140" y2="120" strokeDasharray="2,2" />
          <line x1="140" y1="80" x2="100" y2="120" strokeDasharray="2,2" />
          <line x1="140" y1="160" x2="180" y2="200" strokeDasharray="2,2" />
          <line x1="180" y1="160" x2="140" y2="200" strokeDasharray="2,2" />
        </svg>
      </div>

      <motion.div
        variants={containerVariants}
        initial="hidden"
        whileInView="visible"
        viewport={{ once: true, margin: "-100px" }}
        className="max-w-[1400px] mx-auto px-5 md:px-6 lg:px-7 xl:px-8 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-12 gap-12 mb-16 relative z-10"
      >
        {/* Column 1: Brand */}
        <motion.div variants={columnVariants} className="lg:col-span-4 flex flex-col items-start relative">
          {/* Logo Brand Group */}
          <div className="-mt-7 -ml-6 -mb-2 text-white w-full max-w-[200px] relative z-20">
            <img
              src={whiteMabLogo}
              alt="Maabany Logo"
              className="w-full h-auto object-contain"
              onError={(e) => {
                (e.target as HTMLImageElement).src = "/Maabany white.png";
              }}
            />
          </div>

          <p className="text-[14px] text-white/80 leading-[1.8] font-light pr-4">
            Maabany Integrated Building Solutions delivers innovative engineering, construction, and facility management services across the Kingdom of Saudi Arabia (KSA) with a commitment to quality, precision, and long-term value.
          </p>

          {/* Social media icons */}
          <div className="flex items-center gap-3 pt-4">
            {socialLinks.map((social, i) => (
              <a
                key={i}
                href={social.href}
                target="_blank"
                rel="noopener noreferrer"
                title={social.name}
                className="w-9 h-9 rounded-full border border-white/20 flex items-center justify-center text-white/70 hover:text-white hover:border-primary hover:bg-primary transition-all duration-250 transform hover:scale-110"
              >
                <social.icon className="w-4 h-4" />
              </a>
            ))}
          </div>
        </motion.div>

        {/* Column 2: Navigation */}
        <motion.div variants={columnVariants} className="lg:col-span-3 space-y-6">
          <h4 className="text-[18px] font-semibold text-white tracking-wide relative pb-2 after:content-[''] after:absolute after:bottom-0 after:left-0 after:w-8 after:h-[2px] after:bg-primary">
            Quick Links
          </h4>
          <ul className="grid grid-cols-1 gap-3.5">
            {quickLinks.map((link, i) => (
              <li key={i}>
                <Link
                  to={link.path}
                  onClick={(e) => handleFooterLinkClick(e, link.path)}
                  className="text-[15px] text-white/80 hover:text-primary transition-all duration-300 inline-flex items-center gap-2 group relative py-1"
                >
                  <span className="w-1.5 h-1.5 rounded-full bg-white/20 group-hover:bg-primary group-hover:shadow-[0_0_8px_rgba(234,138,34,0.6)] transition-all" />
                  <span className="relative">
                    {link.label}
                    <span className="absolute bottom-0 left-0 w-0 h-[1.5px] bg-primary transition-all duration-300 group-hover:w-full" />
                  </span>
                </Link>
              </li>
            ))}
          </ul>
        </motion.div>

        {/* Column 3: Resources */}
        <motion.div variants={columnVariants} className="lg:col-span-2 space-y-6">
          <h4 className="text-[18px] font-semibold text-white tracking-wide relative pb-2 after:content-[''] after:absolute after:bottom-0 after:left-0 after:w-8 after:h-[2px] after:bg-primary">
            Resources
          </h4>
          <ul className="grid grid-cols-1 gap-3.5 mb-6">
            {resourceLinks.map((link, i) => (
              <li key={i}>
                {link.label === 'Company Profile' ? (
                  <button
                    onClick={downloadCompanyProfile}
                    className="text-[15px] text-white/80 hover:text-primary text-left transition-all duration-300 inline-flex items-center gap-2 group cursor-pointer focus:outline-none relative py-1"
                  >
                    <span className="w-1.5 h-1.5 rounded-full bg-white/20 group-hover:bg-primary group-hover:shadow-[0_0_8px_rgba(234,138,34,0.6)] transition-all" />
                    <span className="relative">
                      {link.label}
                      <span className="absolute bottom-0 left-0 w-0 h-[1.5px] bg-primary transition-all duration-300 group-hover:w-full" />
                    </span>
                  </button>
                ) : (
                  <Link
                    to={link.path}
                    onClick={(e) => handleFooterLinkClick(e, link.path)}
                    className="text-[15px] text-white/80 hover:text-primary transition-all duration-300 inline-flex items-center gap-2 group relative py-1"
                  >
                    <span className="w-1.5 h-1.5 rounded-full bg-white/20 group-hover:bg-primary group-hover:shadow-[0_0_8px_rgba(234,138,34,0.6)] transition-all" />
                    <span className="relative">
                      {link.label}
                      <span className="absolute bottom-0 left-0 w-0 h-[1.5px] bg-primary transition-all duration-300 group-hover:w-full" />
                    </span>
                  </Link>
                )}
              </li>
            ))}
            <li>
              <button
                onClick={() => setQuoteModalOpen(true)}
                className="text-[15px] text-white/80 hover:text-primary text-left transition-all duration-300 inline-flex items-center gap-2 group cursor-pointer focus:outline-none relative py-1"
              >
                <span className="w-1.5 h-1.5 rounded-full bg-white/20 group-hover:bg-primary group-hover:shadow-[0_0_8px_rgba(234,138,34,0.6)] transition-all" />
                <span className="relative">
                  Request a Quote
                  <span className="absolute bottom-0 left-0 w-0 h-[1.5px] bg-primary transition-all duration-300 group-hover:w-full" />
                </span>
              </button>
            </li>
          </ul>
        </motion.div>

        {/* Column 4: Contact Us */}
        <motion.div variants={columnVariants} className="lg:col-span-3 space-y-6">
          <h4 className="text-[18px] font-semibold text-white tracking-wide relative pb-2 after:content-[''] after:absolute after:bottom-0 after:left-0 after:w-8 after:h-[2px] after:bg-primary">
            Contact Us
          </h4>
          <div className="space-y-4 text-[14px] text-white/75 font-light">
            <div className="flex gap-3 items-start group">
              <div className="p-2.5 rounded-[12px] border border-white/15 text-primary shrink-0 group-hover:bg-primary group-hover:text-white transition-all duration-300">
                <MapPin className="w-4 h-4" />
              </div>
              <div className="space-y-1 mt-0.5">
                <p className="font-medium text-white text-[14px]">Jeddah Office (SA)</p>
                <a
                  href="https://maps.google.com/?q=2923+Al-Sharif+Ahmed+bin+Abdul+Muttalib,+Al-Salhiya+District,+Jeddah,+Saudi+Arabia"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-white/60 text-[12px] leading-relaxed hover:text-primary transition-colors block"
                >
                  2923 Al-Sharif Ahmed bin Abdul Muttalib, Al-Salhiya District, Jeddah, Saudi Arabia
                </a>
              </div>
            </div>

            <div className="flex gap-3 items-start group">
              <div className="p-2.5 rounded-[12px] border border-white/15 text-primary shrink-0 group-hover:bg-primary group-hover:text-white transition-all duration-300">
                <MapPin className="w-4 h-4" />
              </div>
              <div className="space-y-1 mt-0.5">
                <p className="font-medium text-white text-[14px]">Cairo Office (Egy)</p>
                <a
                  href="https://maps.google.com/?q=53+Hassan+El+Sherif+Street,+Nasr+City,+Cairo,+Egypt"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-white/60 text-[12px] leading-relaxed hover:text-primary transition-colors block"
                >
                  53 Hassan El Sherif Street, Nasr City, Cairo, Egypt
                </a>
              </div>
            </div>

            <div className="flex gap-3 items-start">
              <div className="p-2.5 rounded-[12px] border border-white/15 text-primary shrink-0">
                <Mail className="w-4 h-4" />
              </div>
              <div className="space-y-1 mt-0.5">
                <p className="font-medium text-white text-[14px]">Email</p>
                <a
                  href="mailto:sales@maabany.com"
                  className="text-white/60 text-[12px] hover:text-primary transition-colors focus:outline-none focus:underline block"
                >
                  sales@maabany.com
                </a>
              </div>
            </div>
          </div>
        </motion.div>
      </motion.div>

      {/* Bottom Bar */}
      <div className="max-w-7xl mx-auto px-6 lg:px-8 pt-8 flex flex-col sm:flex-row items-center justify-center gap-y-2 gap-x-4 sm:gap-x-6 text-[14px] text-white/60 relative z-10 text-center">
        <p>All Rights Reserved © 2026</p>
        <div className="hidden sm:block w-[1px] h-3.5 bg-white/15" />
        <div className="flex items-center gap-2">
          <span className="text-[12px] text-white/60">Powered by</span>
          <a
            href="https://techhouseksa.com/"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center"
          >
            <img
              src={techHouseLogo}
              alt="Technology House"
              className="h-7 md:h-8 w-auto opacity-95 hover:opacity-100 transition-opacity cursor-pointer"
              onError={(e) => {
                (e.target as HTMLImageElement).src = "/TEH V 2.png";
              }}
            />
          </a>
        </div>
      </div>
    </footer>
  );
}
