// src/app/shared/components/header/header.component.ts
import { Component, signal, inject, DestroyRef, afterNextRender } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { fromEvent, asyncScheduler } from 'rxjs';
import { throttleTime } from 'rxjs/operators';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { IconsComponent } from '../icons/icons.component';
import { HeaderSearchComponent } from '../header-search/header-search.component';
import { MobileNavComponent } from '../mobile-nav/mobile-nav.component';

@Component({
  selector: 'app-header',
  imports: [RouterLink, RouterLinkActive, IconsComponent, HeaderSearchComponent, MobileNavComponent],
  templateUrl: './header.component.html',
  styleUrl: './header.component.css'
})
export class HeaderComponent {
  private readonly destroyRef = inject(DestroyRef);

  readonly menuOpen = signal<boolean>(false);
  readonly searchOpen = signal<boolean>(false);
  readonly currentLang = signal<'EN' | 'AR'>('EN');
  readonly isScrolled = signal<boolean>(false);

  constructor() {
    afterNextRender(() => {
      this.scrollTrigger();
    });
  }

  scrollTrigger() {
    fromEvent(window, 'scroll')
      .pipe(
        throttleTime(100, asyncScheduler, { leading: true, trailing: true }),
        takeUntilDestroyed(this.destroyRef)
      )
      .subscribe(() => {
        const scrolled = window.scrollY > 20;
        if (this.isScrolled() !== scrolled) {
          this.isScrolled.set(scrolled);
        }
      });
  }

  readonly navLinks = [
    { label: 'Home', path: '/' },
    { label: 'About', path: '/about' },
    { label: 'Solutions', path: '/solutions' },
    { label: 'Projects', path: '/projects' },
    { label: 'Industries We Serve', path: '/industries' },
    { label: 'Clients & Partners', path: '/clients-partners' },
    { label: 'Blogs', path: '/blogs' },
    { label: 'Contact Us', path: '/contact' }
  ];

  toggleMenu(): void {
    this.menuOpen.update(val => !val);
  }

  toggleSearch(): void {
    this.searchOpen.update(val => !val);
  }

  toggleLang(): void {
    this.currentLang.update(l => l === 'EN' ? 'AR' : 'EN');
  }
}

<header class="fixed top-0 left-0 right-0 z-50 pointer-events-none w-full">
  <div
    class="relative w-full max-w-350 mx-auto px-5 md:px-6 pt-(--hero-nav-top-spacing) lg:px-7 xl:px-8 transition-transform duration-300"
    [class]="isScrolled() ? 'translate-y-0':'translate-y-5'">
    <!-- Nav Pill Container -->
    <div
      class="pointer-events-auto w-full rounded-full bg-white/95 backdrop-blur-md border border-neutral-200 py-3 px-6 md:px-8 flex items-center justify-between shadow-xl">
      <!-- Brand Logo -->
      <a routerLink="/" class="relative flex items-center w-40 h-10 md:w-52 md:h-11 group">
        <img src="/main-logo.png" width="125" height="52" loading="lazy" decoding="async"
          alt="Maabany Integrated Building Solutions"
          class="h-11.25 md:h-13 w-auto object-contain transition-transform duration-300 group-hover:scale-105" />
      </a>

      <!-- Desktop Nav Links -->
      <nav class="hidden xl:flex items-center gap-2 xl:gap-3">
        @for (link of navLinks; track link.path) {
        <a [routerLink]="link.path" routerLinkActive="text-[#EA8A22] font-bold"
          [routerLinkActiveOptions]="{ exact: link.path === '/' }"
          class="px-3 py-1.5 rounded-full text-[13px] font-semibold text-[#142b52] hover:text-[#EA8A22] transition-colors relative">
          {{ link.label }}
        </a>
        }
      </nav>

      <!-- Right Action Items -->
      <div class="flex items-center gap-3">
        <!-- Search Trigger -->
        <button (click)="toggleSearch()"
          class="flex items-center justify-center p-2.5 rounded-full bg-transparent hover:bg-neutral-100 cursor-pointer transition-colors"
          title="Search structural projects">
          <app-icons icon="search" [width]="20" [height]="20" />
        </button>

        <!-- Language Toggle -->
        <button (click)="toggleLang()"
          class="hidden md:flex items-center gap-1.5 px-3 py-1.5 rounded-full font-mono text-xs font-bold text-neutral-600 hover:bg-neutral-100 transition-colors">
          🌐 <span>{{ currentLang() }}</span>
        </button>

        <!-- Request a Quote CTA Button -->
        <a href="#"
          class="hidden sm:inline-flex items-center justify-center px-5 py-2.5 bg-[#EA8A22] hover:bg-[#EA8A22]/90 text-white font-bold text-xs uppercase tracking-wider rounded-full shadow-lg shadow-[#EA8A22]/20 hover:shadow-[#EA8A22]/30 transition-all font-mono">
          Request A Quote
        </a>

        <!-- Mobile Menu Hamburger -->
        <button (click)="toggleMenu()"
          class="xl:hidden w-10 h-10 rounded-full bg-neutral-100 hover:bg-neutral-200 flex items-center justify-center text-[#142b52] font-bold transition-colors">
          {{ menuOpen() ? '✕' : '☰' }}
        </button>
      </div>
    </div>

    <!-- Search Overlay Box -->
    @if (searchOpen()) {
    <div animate.enter="enter-animation" animate.leave="leaving"
      class="pointer-events-auto mt-3 rounded-2xl border border-neutral-200 bg-white/95 backdrop-blur-xl p-4 shadow-2xl">
      <app-header-search (close)="searchOpen.set(false)" />
    </div>
    }

  </div>

  <!-- Mobile Offcanvas Navigation Component (outside transformed container for full viewport coverage) -->
  <app-mobile-nav [isOpen]="menuOpen()" [navLinks]="navLinks" [currentLang]="currentLang()"
    (close)="menuOpen.set(false)" (toggleLang)="toggleLang()" />
</header>

// react-project/src/components/Header.tsx
import React, { useState, useEffect } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { Search, Globe, Menu, X, ChevronRight } from 'lucide-react';
import { useQuoteModal } from '../contexts/QuoteContext';

import maabanyLogo from '../assets/images/maabany_logo_transparent-1.png';

interface HeaderProps {
  isHeroVariant?: boolean;
  activeSection?: string;
}

export function Header({ isHeroVariant = true, activeSection = 'home' }: HeaderProps) {
  const location = useLocation();
  const navigate = useNavigate();
  const setQuoteModalOpen = useQuoteModal();

  const [menuOpen, setMenuOpen] = useState(false);
  const [searchOpen, setSearchOpen] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const [scrolled, setScrolled] = useState(false);

  // Sync searchQuery with "?q=" URL query param when on /search page
  useEffect(() => {
    const params = new URLSearchParams(location.search);
    const q = params.get('q') || '';
    if (location.pathname === '/search') {
      setSearchQuery(q);
    } else {
      setSearchQuery('');
    }
  }, [location]);

  // Close mobile menu on route changes
  useEffect(() => {
    setMenuOpen(false);
  }, [location.pathname]);

  // Monitor the scroll position of our custom app scroller viewport
  useEffect(() => {
    const scroller = document.getElementById('app-scroller');
    if (!scroller) return;

    const handleScroll = () => {
      setScrolled(scroller.scrollTop > 15);
    };

    scroller.addEventListener('scroll', handleScroll);
    handleScroll(); // execute once on mount

    return () => {
      scroller.removeEventListener('scroll', handleScroll);
    };
  }, []);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        if (searchOpen) {
          setSearchOpen(false);
          setSearchQuery('');
        }
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [searchOpen]);

  const [currentLang, setCurrentLang] = useState<'EN' | 'AR'>('EN');

  // Single source of truth for all navigation items
  const allNavigationItems = [
    { id: 'home', label: 'Home', path: '/', type: 'standard' },
    { id: 'about', label: 'About', path: '/about', type: 'standard' },
    { id: 'solutions', label: 'Solutions', path: '/solutions', type: 'standard' },
    { id: 'projects', label: 'Projects', path: '/projects', type: 'standard' },
    { id: 'industries', label: 'Industries We Serve', path: '/industries', type: 'standard' },
    { id: 'clients', label: 'Clients & Partners', path: '/clients-partners', type: 'standard' },
    { id: 'blogs', label: 'Blogs', path: '/blogs', type: 'standard' },
    { id: 'contact', label: 'Contact Us', path: '/contact', type: 'standard' },
    { id: 'search', label: 'Search', path: '/search', type: 'special' },
    { id: 'request-quote', label: 'Request A Quote', path: '/request-quote', type: 'cta' },
  ];

  const navLinks = allNavigationItems.filter(item => item.type === 'standard');

  // Reusable keyboard focus classes for WCAG AA compliance
  const focusRingClass = `focus-visible:ring-2 focus-visible:ring-primary focus-visible:outline-none focus-visible:ring-offset-2 focus-visible:ring-offset-white`;

  const handleLinkClick = (e: React.MouseEvent<HTMLAnchorElement>, path: string) => {
    if (location.pathname === path) {
      setMenuOpen(false);
      const scroller = document.getElementById('app-scroller');
      if (scroller) {
        e.preventDefault();
        scroller.scrollTo({
          top: 0,
          behavior: 'smooth'
        });
      }
    }
  };

  return (
    <header
      id={isHeroVariant ? "hero-header" : "global-header"}
      className="fixed top-0 left-0 right-0 z-50 pointer-events-none w-full"
    >
      <div
        className="relative w-full max-w-[1400px] mx-auto px-5 md:px-6 lg:px-7 xl:px-8 transition-all duration-300"
        style={{
          paddingTop: scrolled
            ? '12px'
            : isHeroVariant
              ? 'calc(var(--hero-nav-top-spacing, 16px) + var(--outer-padding-top, 16px))'
              : 'calc(var(--outer-padding-top, 16px) + 12px)'
        }}
      >
        <div
          id="nav-pill"
          className={`pointer-events-auto w-full rounded-full transition-all duration-300 flex items-center justify-between ${scrolled
              ? 'bg-white/95 backdrop-blur-md border border-neutral-200 py-2.5 px-5 md:px-7'
              : 'bg-white border border-neutral-100 py-3.5 px-6 md:px-8'
            }`}
        >
          <Link
            to="/"
            onClick={(e) => handleLinkClick(e, '/')}
            className={`relative flex items-center w-40 h-10 md:w-56 md:h-12 group transition-all duration-300 transform hover:scale-[1.02] active:scale-95 ${focusRingClass}`}
          >
            <img
              src={maabanyLogo || "/maabany_logo_transparent-1.png"}
              alt="Maabany Integrated Building Solutions"
              className="absolute left-0 top-1/2 -translate-y-1/2 h-[45px] md:h-[55px] w-auto max-w-none object-contain transition-all duration-300 group-hover:scale-102"
              referrerPolicy="no-referrer"
              onError={(e) => {
                // Fallback to static public logo URL if bundler path fails
                (e.target as HTMLImageElement).src = "/maabany_logo_transparent-1.png";
              }}
            />
          </Link>

          <nav className="hidden xl:flex items-center gap-2 xl:gap-3">
            {navLinks.map((link) => {
              const isActive =
                location.pathname === link.path ||
                (link.id === 'solutions' && location.pathname.startsWith('/solutions')) ||
                (link.id === 'projects' && location.pathname.startsWith('/projects')) ||
                (link.id === 'industries' && location.pathname.startsWith('/industries'));

              const linkColor = isActive
                ? 'text-primary font-semibold'
                : 'text-[#142b52] hover:text-primary font-semibold';

              return (
                <Link
                  key={link.id}
                  to={link.path}
                  onClick={(e) => handleLinkClick(e, link.path)}
                  className={`flex items-center py-1.5 px-2 2xl:px-2.5 rounded-full text-[12.5px] whitespace-nowrap tracking-wide transition-colors relative duration-300 ${linkColor} ${focusRingClass}`}
                >
                  {link.label}
                  <span
                    className={`absolute bottom-0 left-2 right-2 h-[2px] bg-primary transition-all duration-300 ${isActive ? 'opacity-100' : 'opacity-0 hover:opacity-100'
                      }`}
                  />
                </Link>
              );
            })}
          </nav>

          <div className="flex items-center gap-2.5 xl:gap-3">
            <div className="relative">
              <button
                onClick={() => setSearchOpen(!searchOpen)}
                className={`p-2.5 rounded-full transition-all duration-200 ${focusRingClass} hover:bg-neutral-100 text-neutral-500 hover:text-neutral-800`}
                title="Search structural projects"
              >
                <Search className="w-5 h-5" />
              </button>
            </div>

            <button
              onClick={() => setCurrentLang(prev => prev === 'EN' ? 'AR' : 'EN')}
              className={`hidden md:flex items-center gap-1.5 p-2 rounded-full transition-colors duration-200 font-mono text-xs font-bold ${focusRingClass} text-neutral-500 hover:text-neutral-800 hover:bg-neutral-100`}
              title="Change Language"
            >
              <Globe className="w-4 h-4" />
              <span>{currentLang}</span>
            </button>

            {(() => {
              const cta = allNavigationItems.find(item => item.type === 'cta');
              if (!cta) return null;
              return (
                <Link
                  to={cta.path}
                  onClick={(e) => handleLinkClick(e, cta.path)}
                  className={`hidden sm:inline-flex items-center justify-center whitespace-nowrap shrink-0 px-5 py-2.5 font-semibold text-xs tracking-wider uppercase rounded-full shadow-lg transition-all duration-300 transform active:scale-95 cursor-pointer font-mono ${focusRingClass} ${location.pathname === cta.path
                      ? 'bg-primary text-white shadow-primary/25 ring-2 ring-primary'
                      : 'bg-primary hover:bg-primary/90 text-white shadow-primary/10 hover:shadow-primary/25'
                    }`}
                >
                  {cta.label}
                </Link>
              );
            })()}

            <button
              onClick={() => setMenuOpen(!menuOpen)}
              className={`xl:hidden relative flex items-center justify-center w-10 h-10 rounded-full transition-colors ${focusRingClass} text-[#142b52] bg-neutral-100 hover:bg-neutral-200`}
            >
              <Menu className={`w-5 h-5 absolute transition-all duration-300 ${menuOpen ? 'opacity-0 rotate-90 scale-50' : 'opacity-100 rotate-0 scale-100'}`} />
              <X className={`w-5 h-5 absolute transition-all duration-300 ${menuOpen ? 'opacity-100 rotate-0 scale-100' : 'opacity-0 -rotate-90 scale-50'}`} />
            </button>
          </div>
        </div>

        {searchOpen && (
          <div className="px-3 w-full">
            <div
              className="pointer-events-auto mt-3 rounded-2xl border border-neutral-200 bg-white/95 backdrop-blur-xl text-neutral-900 p-4 shadow-xl shadow-neutral-200/50 animate-fade-in"
              style={{
                marginLeft: '12px',
                marginRight: '12px',
                width: 'calc(100% - 24px)'
              }}
            >
              <form
                onSubmit={(e) => {
                  e.preventDefault();
                  if (searchQuery.trim()) {
                    navigate(`/search?q=${encodeURIComponent(searchQuery.trim())}`);
                    setSearchOpen(false);
                  }
                }}
                className="max-w-4xl mx-auto flex items-center gap-3"
              >
                <Search className="w-5 h-5 text-neutral-600" />
                <input
                  type="text"
                  placeholder="Search solutions, projects, cities..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="flex-1 bg-transparent border-none focus:outline-none text-sm py-1 text-neutral-900 placeholder-neutral-400"
                  autoFocus
                />
                <button
                  type="button"
                  onClick={() => { setSearchOpen(false); setSearchQuery(''); }}
                  className={`text-xs font-mono px-3 py-1.5 rounded-lg transition-colors ${focusRingClass} text-neutral-600 hover:text-neutral-900 bg-neutral-100 hover:bg-neutral-200`}
                >
                  Close ESC
                </button>
              </form>
            </div>
          </div>
        )}

        <div className={`xl:hidden absolute left-0 right-0 z-50 origin-top transition-all duration-300 ${menuOpen ? 'opacity-100 scale-100 pointer-events-auto' : 'opacity-0 scale-95 pointer-events-none'
          }`}
          style={{
            top: '100%',
            paddingLeft: 'var(--outer-padding-x, 24px)',
            paddingRight: 'var(--outer-padding-x, 24px)',
            marginTop: '12px'
          }}
        >
          <div
            className={`${menuOpen ? 'pointer-events-auto' : 'pointer-events-none'} rounded-2xl border border-neutral-200 bg-white/98 backdrop-blur-xl text-neutral-900 p-3 shadow-2xl shadow-neutral-200/60 mx-3 max-h-[calc(100vh-140px)] overflow-y-auto scrollbar-none`}
          >
            <div className="flex flex-col space-y-1">
              {allNavigationItems.map((link) => {
                const isActive =
                  location.pathname === link.path ||
                  (link.id === 'solutions' && location.pathname.startsWith('/solutions')) ||
                  (link.id === 'projects' && location.pathname.startsWith('/projects')) ||
                  (link.id === 'industries' && location.pathname.startsWith('/industries'));

                if (link.type === 'cta') {
                  return (
                    <Link
                      key={link.id}
                      to={link.path}
                      onClick={(e) => handleLinkClick(e, link.path)}
                      className={`mt-2 mx-1 px-5 py-3.5 rounded-xl text-sm font-bold tracking-wider uppercase font-mono transition-all duration-300 bg-primary text-white hover:bg-primary/90 flex items-center justify-between shadow-lg active:scale-[0.99] ${focusRingClass}`}
                    >
                      <span>{link.label}</span>
                      <ChevronRight className="w-4 h-4 text-white" />
                    </Link>
                  );
                }

                if (link.id === 'search') {
                  return (
                    <Link
                      key={link.id}
                      to={link.path}
                      onClick={(e) => {
                        handleLinkClick(e, link.path);
                        setSearchOpen(true);
                      }}
                      className={`px-5 py-3.5 rounded-xl text-sm font-semibold transition-all duration-200 border-b border-neutral-100 flex items-center justify-between ${focusRingClass} ${isActive
                          ? 'text-primary bg-neutral-50 font-bold'
                          : 'text-neutral-700 hover:text-primary hover:bg-neutral-50'
                        }`}
                    >
                      <div className="flex items-center gap-2">
                        <Search className="w-4 h-4 text-neutral-500" />
                        <span>{link.label}</span>
                      </div>
                      <ChevronRight className={`w-4 h-4 transition-transform duration-200 ${isActive ? 'text-primary translate-x-1 opacity-100' : 'opacity-50'}`} />
                    </Link>
                  );
                }

                return (
                  <Link
                    key={link.id}
                    to={link.path}
                    onClick={(e) => handleLinkClick(e, link.path)}
                    className={`px-5 py-3.5 rounded-xl text-sm font-semibold transition-all duration-200 border-b border-neutral-100 flex items-center justify-between ${focusRingClass} ${isActive
                        ? 'text-primary bg-neutral-50 font-bold'
                        : 'text-neutral-700 hover:text-primary hover:bg-neutral-50'
                      }`}
                  >
                    <span>{link.label}</span>
                    <ChevronRight className={`w-4 h-4 transition-transform duration-200 ${isActive ? 'text-primary translate-x-1 opacity-100' : 'opacity-50'}`} />
                  </Link>
                );
              })}

              {/* Language Switcher for mobile inside the list */}
              <button
                onClick={() => {
                  setCurrentLang(prev => prev === 'EN' ? 'AR' : 'EN');
                  setMenuOpen(false);
                }}
                className={`px-5 py-3.5 rounded-xl text-sm font-semibold transition-all duration-200 border-b border-neutral-100 flex items-center justify-between w-full text-left ${focusRingClass} text-neutral-700 hover:text-primary hover:bg-neutral-50`}
              >
                <div className="flex items-center gap-2">
                  <Globe className="w-4 h-4 text-neutral-500" />
                  <span>Language</span>
                </div>
                <span className="font-mono text-xs font-bold px-2 py-1 bg-neutral-100 rounded text-neutral-600">
                  {currentLang}
                </span>
              </button>
            </div>
          </div>
        </div>
      </div>
    </header>
  );
}
